name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Get your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Build Docker image
      - name: Build Docker image
        run: docker build -t myapp .

      # 3. Run container
      - name: Run container
        run: docker run -d -p 8000:8000 -e DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} myapp

      # 4. Show running containers
      - name: Check containers
        run: docker ps -a

      # 5. Show container logs (VERY IMPORTANT)
      - name: Show container logs
        run: docker logs $(docker ps -aq | head -n 1)

      # 6. Wait for app to start
      - name: Wait for app
        run: sleep 15

      # 7. Test if app works
      - name: Test app
        run: curl http://localhost:8000